server:
  port: 9000
kafka:
  bootstrap-address: localhost:9092
  consumer:
    bootstrap-servers: localhost:9092
    group-id: <put here the group id of kafka>
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  topic-name: <put here the topic>
mongodb:
  config:
    user: <put here your user>
    password: <put here your password>
    database: <put here the name of your bd>
    port: 27017
    url: <put here your mongo url>

