spring:
  data:
    mongodb:
      authentication-database: admin
      username: test
      password: test
      database: initial
      port: 27017
      url: initialha0.mqyld.mongodb.net/initial?retryWrites=true&w=majority